export const action_types={
    ADD_TO_CART:'ADD_TO_CART',
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    RESET_CART:'RESET_CART',
    INCREASE_ITEM_QUANTITY:'INCREASE_ITEM_QUANTITY',
    DECREASE_ITEM_QUANTITY:'DECREASE_ITEM_QUANTITY',

}