export const ActionTypes={
    GET_PRODUCTS_REQUEST:'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS:'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL:'GET_PRODUCTS_FAIL',
    GET_PRODUCTDETAILS_REQUEST:'GET_PRODUCTDETAILS_REQUEST',
    GET_PRODUCTDETAILS_SUCCESS:'GET_PRODUCTDETAILS_SUCCESS',
    GET_PRODUCTDETAILS_FAIL:'GET_PRODUCTDETAILS_FAIL',
    GET_PRODUCTDETAILS_RESET:'GET_PRODUCTDETAILS_RESET'
}